// Code generated by "go run gen/gen.go"; DO NOT EDIT.

package config

type GoogleIdentityPlatform struct {
	CredentialsJSONFilePath string `mapstructure:"credentials-json-file-path"`
}

func (c *GoogleIdentityPlatform) GetString(key string) string {
	switch key {
	case "credentials-json-file-path":
		return c.CredentialsJSONFilePath
	default:
		return ""
	}
}

func (c *GoogleIdentityPlatform) GetBool(key string) bool {
	return false
}

func (c *GoogleIdentityPlatform) GetInt(key string) int {
	return 0
}

func (c *GoogleIdentityPlatform) GetStringSlice(key string) []string {
	return nil
}

func (c *GoogleIdentityPlatform) GetStringMap(key string) map[string]any {
	return nil
}
